default: &default
  adapter: sqlite3
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: db/tetran_msk_development.sqlite3

test:
  <<: *default
  database: db/tetran_msk_test.sqlite3

production:
  <<: *default
  database: db/tetran_msk_production.sqlite3
