default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= Rails.application.credentials.dig(:database, :username) %>
  password: <%= Rails.application.credentials.dig(:database, :password) %>

development:
  <<: *default
  database: tetran_msk_development

test:
  <<: *default
  database: tetran_msk_test

production:
  <<: *default
  database: tetran_msk_production

